CREATE TABLE IF NOT EXISTS `github_profiles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `github_id` int NOT NULL,
  `username` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `bio` text,
  `avatar_url` varchar(255) DEFAULT NULL,
  `profile_url` varchar(255) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `blog` varchar(255) DEFAULT NULL,
  `twitter_username` varchar(255) DEFAULT NULL,
  `public_repos` int DEFAULT '0',
  `followers` int DEFAULT '0',
  `following` int DEFAULT '0',
  `total_stars` int DEFAULT '0',
  `total_forks` int DEFAULT '0',
  `total_watchers` int DEFAULT '0',
  `most_starred_repo` varchar(255) DEFAULT NULL,
  `most_forked_repo` varchar(255) DEFAULT NULL,
  `account_age_days` int DEFAULT '0',
  `avg_stars_per_repo` float DEFAULT '0',
  `avg_forks_per_repo` float DEFAULT '0',
  `languages_used` json DEFAULT NULL,
  `analysis_score` float DEFAULT '0',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `github_id` (`github_id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
